name: github_stars
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  github_sign_in: ^0.0.5-dev.4
  fluttertoast: ^8.0.9
  loading_indicator: ^3.1.0
  flutter_secure_storage: ^5.0.2
  dio: ^4.0.6
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/